name: test-workflow
on: [release]

jobs:
  test:
    runs-on: macos-latest
    steps:       
      - name: make some noise
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      
        
